##PYthon  IN Build Functions

In [9]:
import pandas as pd
import numpy as np
a = np.array([ 10 , 20 , np.nan , 30 , 20 , 40 , 50 , np.nan , 40 , 50 , 60 , np.nan , 70 , np.nan , 80])
se = pd.Series(a)

se.unique()

array([10., 20., nan, 30., 40., 50., 60., 70., 80.])

In [10]:
print(len(se))
print(max(se))
print(min(se))
print(type(se))

print(dir(se))

15
80.0
10.0
<class 'pandas.Series'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__firstlineno__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__static_attributes__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append_internal', '_arith_method', '_attrs', '_binop', '_can_hold_na', '_check_copy_deprecation', '_check_inplace_and_allows_duplicate_labels', '_check_label_or_level_ambiguity', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_expanddim', '_constructor_expanddim_from_mgr', '_constructor_from_mgr', '_dir_additions', '_dir_deletions', '_drop_axis', '_drop_labels_or_levels', '_duplicated', '_find_valid_index', '_flags', '_flex_method', '_from_mgr', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_index_resolvers', '_get_label_or_level_values', '_get_numeric_data', '_get_rows_with_mask', '_get_value', '_get_values_tuple', '_get_with', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_init_dict', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_ixs', '_logical_func', '_logical_method', '_map_values', '_memory_usage', '_metadata', '_mgr', '_min_count_stat_function', '_module_source', '_name', '_needs_reindex_multi', '_pad_or_backfill', '_reduce', '_references', '_reindex_axes', '_reindex_indexer', '_reindex_multi', '_reindex_with_indexers', '_rename', '_repr_data_resource_', '_repr_latex_', '_reset_cache', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_labels', '_set_name', '_set_value', '_set_values', '_set_with', '_set_with_engine', '_shift_with_freq', '_slice', '_stat_function', '_stat_function_ddof', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'between', 'between_time', 'bfill', 'case_when', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first_valid_index', 'flags', 'floordiv', 'from_arrow', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'interpolate', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'keys', 'kurt', 'kurtosis', 'last_valid_index', 'le', 'list', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'memory_usage', 'min', 'mod', 'mode', 'mul', 'multiply', 'name', 'nbytes', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pct_change', 'pipe', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'radd', 'rank', 'rdiv', 'rdivmod', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'repeat', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'searchsorted', 'sem', 'set_axis', 'set_flags', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'std', 'struct', 'sub', 'subtract', 'sum', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_frame', 'to_hdf', 'to_json', 'to_latex', 'to_list', 'to_markdown', 'to_numpy', 'to_period', 'to_pickle', 'to_sql', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unique', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']

In [11]:
print(sorted(se))

[10.0, 20.0, nan, 20.0, 30.0, 40.0, 40.0, 50.0, nan, 50.0, 60.0, nan, 70.0, nan, 80.0]

##Typpe Conversion

In [16]:
import numpy as np
import pandas as pd

a = [ 10 , 20 , 30 , 40]
se = pd.Series(a)

print(se.astype(int))

print(se.astype(float))

print(se.astype(bool))

print(se.astype(str))

0    10
1    20
2    30
3    40
dtype: int64
0    10.0
1    20.0
2    30.0
3    40.0
dtype: float64
0    True
1    True
2    True
3    True
dtype: bool
0    10
1    20
2    30
3    40
dtype: str

In [23]:
list(se)

tuple(se)

dict(se)

set(se)

{10, 20, 30, 40}

#   Membership operator

In [ ]:
# check indexing is in or not 

print(0 in se)

print(5 in se)

True
False

In [ ]:
#  check values is in or not 

print(se.isin([10,20,40]))

0     True
1     True
2    False
3     True
dtype: bool

#   Looping over a SERIES

In [34]:
for i in se:
    print(i)

10
20
30
40

In [ ]:
for i in se.keys():
    print(i)

In [33]:
for i ,v in se.items():
    print(i,v)

0 10
1 20
2 30
3 40

In [ ]:


def square(n):
    return n * n
print(se.apply(square))

0     100
1     400
2     900
3    1600
dtype: int64

# AERTHEMATIC Operators

In [41]:
se+5

0    15
1    25
2    35
3    45
dtype: int64

In [42]:
se-4

0     6
1    16
2    26
3    36
dtype: int64

In [43]:
se%2

0    0
1    0
2    0
3    0
dtype: int64

In [44]:
se/2

0     5.0
1    10.0
2    15.0
3    20.0
dtype: float64

In [45]:
se*2

0    20
1    40
2    60
3    80
dtype: int64

In [48]:
a = np.array([1,2,3,4,5])
se2 = pd.Series(a)


se*se2

0     10.0
1     40.0
2     90.0
3    160.0
4      NaN
dtype: float64

# COmparission Operators

In [ ]:
import pandas as pd
import numpy as np

a = np.array([10,20,30,40,50])
se = pd.Series(a)

a = np.array([10,20,3,40,5])
se2 = pd.Series(a)

se>10

se==10

se>=10

se<=10

se!=10

# se

0    False
1     True
2     True
3     True
4     True
dtype: bool

In [86]:
# se>se2
# se<se2

# se>=se2

# se<=se2

# se==se2

# se.equals(se2)

se.compare(se2)

   self  other
0    10      1
1    20      2
2    30      3
3    40      4
4    50      5

In [89]:
import pandas as pd
import numpy as np

a = np.array([1,2,3,5,7])
a2 = np.array([1,2,4,5,8])

se = pd.Series(a)
se2 = pd.Series(a2)

se.compare(se2)

   self  other
2   3.0    4.0
4   7.0    8.0